# Generated by Django 2.2 on 2019-07-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=30)),
                ('name_fa', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=100)),
                ('images_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SomeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rows_count', models.IntegerField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_architect_aide.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_data', models.DateTimeField()),
                ('status_message', models.CharField(max_length=30)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_architect_aide.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_architect_aide.Table')),
            ],
        ),
    ]
