# Generated by Django 2.2 on 2020-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='axiom_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='owl_file',
            field=models.FileField(upload_to='owl'),
        ),
    ]
