# Generated by Django 2.2 on 2019-07-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='run_data',
            new_name='run_date',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='name_en',
        ),
    ]
