# Generated by Django 2.2 on 2019-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0002_auto_20190706_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name_en',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='name_fa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='site',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('table', 'name_en')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('script', 'name_en')},
        ),
    ]
