# Generated by Django 2.2 on 2020-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0002_auto_20200722_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='owl_file',
            field=models.FileField(unique=True, upload_to='owl'),
        ),
    ]
