# Generated by Django 2.2 on 2020-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0003_auto_20200723_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architecture',
            old_name='axiom_count',
            new_name='triple_count',
        ),
    ]
