# Generated by Django 2.2 on 2020-02-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0003_auto_20190706_0442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='column',
            name='table',
        ),
        migrations.RemoveField(
            model_name='run',
            name='script',
        ),
        migrations.DeleteModel(
            name='SomeTable',
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='table',
            name='script',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
