# Generated by Django 2.2 on 2020-07-25 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('software_architect_aide', '0004_auto_20200723_1611'), ]

    operations = [migrations.RemoveField(model_name='architecture', name='last_modified', ), ]
