# Generated by Django 2.2 on 2020-02-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0004_auto_20200204_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('authors', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=30)),
                ('paper', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Script',
        ),
    ]
