# Generated by Django 2.2 on 2020-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_architect_aide', '0005_auto_20200204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(default='در دست بررسی', max_length=30),
        ),
    ]
