# Generated by Django 2.2 on 2020-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('software_architect_aide', '0005_remove_architecture_last_modified'), ]

    operations = [migrations.AddField(model_name='architecture', name='creation_method', field=models.CharField(
        choices=[('manual', 'ساخت دستی'), ('reference', 'براساس معماری مرجع'), ('upload', 'بارگذاری هستان\u200cشناسی')],
        default='salam', max_length=30), preserve_default=False, ), ]
